/*********************************************************************************
 * 
 * Ce fichier contient toutes les constantes nécessaires au fonctionnement du jeu.
 * En particulier les listes de mots et de phrases proposés à l'utilisateur
 * 
 *********************************************************************************/

// Déclaration des tableaux contenant les listes des mots proposés à l'utilisateur
const listeMots = [
    "Cachalot", 
    "Pétunia", 
    "Serviette", 
    "Baleine", 
    "Vaisseau", 
    "Galaxie", 
    "Infini", 
    "Robot", 
    "Paranoïde", 
    "Lunettes", 
    "Dentifrice", 
    "Enigme", 
    "Soleil", 
    "Planète", 
    "Nebuleuse", 
    "Astéroïde", 
    "Espace", 
    "Ordinateur", 
    "Tardis", 
    "Hyperespace", 
    "Aliens", 
    "Etoile", 
    "Comète", 
    "Fusée", 
    "Singularité", 
    "Trou noir", 
    "Cerveau", 
    "Réacteur", 
    "Exoplanète", 
    "Système", 
    "Voyage", 
    "Cosmos", 
    "Météorite", 
    "Galactique", 
    "Temps", 
    "Proton", 
    "Antimatière", 
    "Stellaire", 
    "Quasar", 
    "Vortex"
];

const listePhrases = [
    "Pas de panique !", 
    "La vie, l'univers et le reste", 
    "Merci pour le poisson", 
    "L'essentiel est invisible pour les yeux", 
    "42 est la réponse à tout", 
    "Où allons-nous ?", 
    "Le guide galactique est infaillible", 
    "Une serviette est un outil indispensable", 
    "La réalité dépasse la fiction", 
    "L'esprit est plus vaste que l'univers", 
    "Nous sommes tous faits de poussière d'étoiles", 
    "Le voyage commence avec un seul pas", 
    "Les réponses se trouvent dans les étoiles", 
    "Ne suivez pas les conventions, inventez-les", 
    "Les robots ont aussi des rêves", 
    "L'univers est rempli de mystères", 
    "Les humains sont des voyageurs de l'infini", 
    "Il y a toujours une solution", 
    "Rêver, c'est déjà voyager", 
    "Le passé et le futur se rejoignent", 
    "Naviguer dans le temps est un art", 
    "L'espace est le dernier refuge", 
    "Le silence de l'univers est assourdissant", 
    "Chaque étoile a une histoire à raconter", 
    "L'inconnu est notre plus grand défi", 
    "La science-fiction d'aujourd'hui est la science de demain", 
    "Rien n'est impossible dans l'univers", 
    "L'avenir appartient aux audacieux", 
    "L'aventure est dans chaque battement d'étoile", 
    "Les questions mènent toujours aux réponses", 
    "La galaxie est vaste, mais pas autant que l'imagination"
];
